# Build and Deploy ASP.NET Core App to Azure (Windows)
# Works with .NET 8 and App Service Windows plan (Free tier)

name: Build and Deploy ASP.NET Core App to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up .NET 8
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore TaskManagementPortal.csproj

      # 4️⃣ Build project
      - name: Build
        run: dotnet build TaskManagementPortal.csproj --configuration Release

      # 5️⃣ Publish project to folder
      - name: Publish
        run: dotnet publish TaskManagementPortal.csproj --configuration Release --output ${{ github.workspace }}\publish --self-contained false

      # 6️⃣ Login to Azure using Service Principal (from secrets)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # 7️⃣ Deploy published folder to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fruiz-demo-asp'          
          slot-name: 'Production'
          package: ${{ github.workspace }}\publish
